### ISSUE TITLE
update importer for sequences in slicer core

### ISSUE THREAD

**Issue by pieper** [fedorov/MultiVolumeImporter#41]
importer now fails due to restructuring of sequences now that they are in the core.

Loading a sequence gives this error:

```
DICOM plugin failed to load 'dMRI_dir107_PA - as a 108 frames Volume Sequence by ImagePositionPatient+InstanceNumber' as a 'MultiVolume'.
Traceback (most recent call last):
  File "/home/researcher/Downloads/Slicer-4.11.0-2020-04-19-linux-amd64/bin/../lib/Slicer-4.11/qt-scripted-modules/MultiVolumeImporterPlugin.py", line 700, in load
    sequenceBrowserModule = slicer.modules.sequencebrowser
AttributeError: module 'modules' has no attribute 'sequencebrowser'
```

Error happens after successful import.

https://github.com/fedorov/MultiVolumeImporter/blob/master/MultiVolumeImporterPlugin.py#L699

Also see discussion here: https://github.com/Slicer/Slicer/pull/4873

**Comment by fedorov** [comment]
@lassoan are you going to fix this? (I recall you added sequences support to this plugin)

**Comment by lassoan** [comment]
yes, I will, it's a simple rename

**Comment by lassoan** [comment]
Fixed by https://github.com/fedorov/MultiVolumeImporter/pull/42
